### ISSUE TITLE
flatten structure of maps

### ISSUE THREAD

**Issue by famoser** [mangelio/app#110]
the maps have the following issues:
- [ ] do not create a parent if no text is present (do not create parents like `1.`)
- [ ] do not leave parents with only one child

**Comment by juliand665** [comment]
It looks like, at least in the data I'm getting from the API, every non-top-level map seems to be represented twice (top-level ones are correct): once at its correct place, and once (incorrectly) as a top-level child of the construction site. Hope this insight helps :)

**Comment by juliand665** [comment]
> do not leave parents with only one child
It'd be nice to consider some context, e.g. if you have the following structure:
```
- A
  - 1
  - 2
- B
  - 1
- C
  - 1
  - 2
  - 3
```
you'd probably still want `B` to exist on its own, not just as `B 1`. Although i suppose that wouldn't be too bad either…

**Comment by famoser** [comment]
the rules are getting to complex; we'll need a simpler approach to be predictable to the use what happens. will rethink the automatic approach. closed in favor of #106
