### ISSUE TITLE
Foyer issues

### ISSUE THREAD

**Issue by pleasure2cu** [mangelio/app#28]
- [x] If you append something to an issue description and then click on save instead of enter, the added text won't actually be saved. It only works if you hit enter.
- [ ] If you click on an image it sometimes gets so big that it pushes the button below it off the screen. Good example is the image with the black stain.

**Comment by famoser** [comment]
for number 2 I need a good lightbox implementation, I've created #29

**Comment by famoser** [comment]
proper usecase to want empty text; if image fulfills purpose
