### ISSUE TITLE
Sample Position Tweaks

### ISSUE THREAD

**Issue by juliand665** [mangelio/app#43]
Currently, the sample data generates, for each map, 25 issues, 5 each of which are in the same spot. This is not a realistic portrayal of issue positions; I'd prefer them to each be positioned individually.

Additionally, all issues currently have a position, while issues' positions are specified to be nullable. It would make for more exhaustive testing if some issues were generated without positions.

**Comment by famoser** [comment]
the sample data generation is deterministic to be able reproduce issues easily. I have modified the algorithm to generate more random looking output, and nullable positions.
