### ISSUE TITLE
Give maps a reference to their building

### ISSUE THREAD

**Issue by juliand665** [mangelio/app#46]
Currently, in order to find out which building a map belongs to, clients have to either build up a dictionary from map IDs to building IDs or traverse all buildings' hierarchies to find out which one the map is in. This could be made much more convenient (and efficient) by adding a `buildingID` property to the `Map` object. For external purposes, `buildingID` would never be null, since maps aren't transferred if they don't belong to a building.

**Comment by juliand665** [comment]
The fix for this issue seems to have been surreptitiously undone recently. The iOS app relies on this property; how fast can you get a fix out? I can add in a (not very nice) workaround until then, if necessary.

**Comment by famoser** [comment]
I am sure you meant `constructionSiteID`. Its added in eb854a0, the new version is already published on the dev environment. I also did rename `mapFileId` -> `mapFileID` as requested.
